ci: Remove unnecessary steps.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -23,15 +23,16 @@ jobs:
     - name: Run tests
       run: cargo test --verbose
       id: tests
-      continue-on-error: true
-    - name: Save output binary if tests failed
-      if: always()
-      # && (needs.build.steps.tests.outcome == 'failure')
-      uses: actions/upload-artifact@v3
-      with:
-        name: ci-test-binary
-        path: ./test
-    # is there a better way to upload, but keep the failed status?
-    - name: Error if tests failed
-      if: (needs.build.steps.tests.outcome == 'failure')
-      run: exit 1
+
+    # Leaving this here in case tests start failing in CI again.
+      # continue-on-error: true
+    # - name: Save output binary if tests failed
+    #   if: always()
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: ci-test-binary
+    #     path: ./test
+    # # is there a better way to upload, but keep the failed status?
+    # - name: Error if tests failed
+    #   if: (needs.build.steps.tests.outcome == 'failure')
+    #   run: exit 1
