ci: Save `test` binary when `cargo test` fails.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -16,9 +16,22 @@ jobs:
     - uses: actions/checkout@v2
     - name: Format checks
       run: cargo fmt --check
+    - name: Run clippy
+      run: cargo clippy -- -D warnings
     - name: Build
       run: cargo build --verbose
     - name: Run tests
       run: cargo test --verbose
-    - name: Run clippy
-      run: cargo clippy --verbose
+      id: tests
+      continue-on-error: true
+    - name: Save output binary if tests failed
+      if: always()
+      # && (needs.build.steps.tests.outcome == 'failure')
+      uses: actions/upload-artifact@v3
+      with:
+        name: ci-test-binary
+        path: ./test
+    # is there a better way to upload, but keep the failed status?
+    - name: Error if tests failed
+      if: (needs.build.steps.tests.outcome == 'failure')
+      run: exit 1
